name: fixgo_provider
description: MechNow Partner — แอปสำหรับช่างรับงานซ่อมรถ
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  fixgo_core:
    path: ../../packages/fixgo_core
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
